baseurl: http://www.jekyllstarter.com
sitename: 'Vernon Silver'
tagline: 'A Jekyll Starter Site'
description: 'Senior Writer at Bloomberg News in Rome'
repo:  'https://github.com/...'

#Jekyll Options
# if using more than one Jekyll instance on your local machine
# port: 
paginate: 1
# Permalinks
permalink:  pretty
# Dependencies
markdown: redcarpet
pygments: true
#Pages - store all pages in the _pages directory
include: ['_pages']
relative_permalinks: false # won't need this as of 2.0: Deprecation: Starting in 2.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Also will change exclude directory
exclude: ['readme.md','license.md','Gemfile','links.jsonp', 'CNAME']



# dev options (true/false)
# if site is in production, 'production: true'
production: true
use_pure_css: false
use_jquery:
include_font_awesome:
include_addthis_sharing:

# options (data)
google_analytics_id:  
disqus_id:
addthis_id: ra-52e194380e6e5e78
# CONTACT FORM http://getsimpleform.com/
simple_form_api_token: 57f94b63113c3daca6cee129dd495cf0


#configuration options for http://prose.io editor
prose:
  siteurl: 'http://www.example.com'
  #rooturl: '_posts'
  site: 
  media: 'assets/img'
  metadata:
    _posts/books:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Book Title"
          value: "Book Title"
      - name: "subtitle"
        field:
          element: "text"
          label: "Subtitle"
      - name: "name"
        field:
          element: "text"
          label: "Name/Slug"
          help: "lowercase title with dashes between words"
          placeholder: "the-title-of-the-book"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          help: "/book/name-from-above"
          placeholder: "/book/name-from-above"
      - name: "pub_date"
        field:
          element: "text"
          label: "Publication Date"
          help: "format: YYYY-MM-DD"
          placeholder: "2014-01-01"
      - name: "isbn"
        field:
          element: "text"
          label: "ISBN"
          help: "13 Digit with no spaces"
          placeholder: "978xxxxxxxxxx"
      - name: "isbn_digital"
        field:
          element: "text"
          label: "ISBN Digital"
          help: "13 Digit with no spaces"
          placeholder: "978xxxxxxxxxx"
      - name: "asin"
        field:
          element: "text"
          label: "Amazon ASIN"
          help: "10 Digit with no spaces"
      - name: "asin_kindle"
        field:
          element: "text"
          label: "Amazon Kindle ASIN"
          help: "10 Digit with no spaces"
      - name: "publisher"
        field:
          element: "text"
          label: "Publisher"
      - name: "cover_image"
        field:
          element: "text"
          label: "Cover Image"
          help: "if different than isbn.jpg"
          placeholder: "name.jpg"
      - name: "category"
        field:
          element: "hidden"
          value: "book"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Book Category"
          placeholder: "Choose Tags"
          options:
            - name: "Fiction"
              value: "fiction"
            - name: "Poetry"
              value: "poetry"
            - name: "Screenplay"
              value: "screenplay"
      - name: "layout"
        field:
          element: "hidden"
          value: "book"
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "category"
        field:
          element: "hidden"
          value: "posts"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Title"
          value: "Title"
      - name: published
        field:
          element: "text"
          label: "Status"
          help: "Change to false if you don't want the post to be published"
          value: true
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "Video"
              value: "video"
            - name: "News"
              value: "news"
            - name: "Books"
              value: "books"
    _pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Title"
          value: "Title"
      - name: permalink
        field:
          element: "text"
          label: "Link"
          help: "/page-name/"
      - name: show_in_menu
        field:
          element: "select"
          label: "Show in Menu?"
          options:
            - name: "True"
              value: 'true'
            - name: "False"
              value: 'false'