baseurl: http://vernonsilver.github.io/
sitename: 'Vernon Silver'
description: 'Journalist, Archaeologist'
# do not include  https://github.com/...
repo: 'vernonsilver/vernonsilver.github.io'
branch: master

#Jekyll Options
# if using more than one Jekyll instance on your local machine
# port: 
# paginate tells Jekyll how many posts per page
# paginate: 1
# Permalinks
permalink:  pretty
# Dependencies
markdown: redcarpet
redcarpet:
  extensions: ['autolink', 'smart']
pygments: true
#Pages - store all pages in the _pages directory
include: ['_pages']
relative_permalinks: false # won't need this as of 2.0: Deprecation: Starting in 2.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Also will change exclude directory
exclude: ['readme.md','license.md','Gemfile','links.jsonp', 'CNAME', 'rakefile']



# dev options (true/false)
# if site is in production, 'production: true'
production: false
use_pure_css: false
use_jquery: false
include_font_awesome: false
include_addthis_sharing:

# options (data)
google_analytics_id:  
disqus_id:
addthis_id: ra-52e194380e6e5e78
# CONTACT FORM http://getsimpleform.com/
simple_form_api_token: 

# options (social)
facebook_id: pages/The-Lost-Chalice/36279809755
twitter_id: vtsilver

#configuration options for http://prose.io editor
prose:
  siteurl: 'http://vernonsilver.com/'
  #rooturl: '_posts'
  site: 
  media: 'assets/img'
  ignore:
    - .gitignore
    - 404.html
    - CNAME
    - atom.xml
    - favicon.ico
    - license.md
    - readme.md
    - robots.txt
    - _config.yml
    - /assets
    - /_layouts
    - /_includes
    - /_site
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Title"
          value: "Title"
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "date"
        field:
          element: "hidden"
      - name: old_permalink
        field:
          element: "hidden"
      - name: "category"
        field:
          element: "select"
          label: "Category"
          options:
            - name: "News"
              value: "news"
            - name: "Media"
              value: "media"
      - name: published
        field:
          element: "checkbox"
          label: "Status"
          help: "Change to false if you don't want the post to be published"
          value: true
    _pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Title"
          value: "Title"
      - name: permalink
        field:
          element: "text"
          label: "Link"
          help: "/page-name/"
      - name: include
        field:
          label: 'Include Snippet'
          element: "text"
          label: "snippet"
      - name: sharing
        field:
          element: "text"
          label: "Add Sharing Buttons to this page?"
          help: "Change to true if you want sharing buttons to show up on the page."
          value: false
      - name: published
        field:
          help: "Change to false if you don't want the post to be published"
          element: "select"
          label: "Published Status"
          options:
            - value: "true"
            - value: "false"
